/**
 * Curated scholarship seed data merged with Tavily web results.
 * Each entry uses a stable id for exclude-on-regenerate logic.
 */

const SEED_SCHOLARSHIPS = [
  {
    id: "seed-national-merit",
    name: "National Merit Scholarship Program",
    sponsor: "National Merit Scholarship Corporation",
    url: "https://www.nationalmerit.org/",
    amountMin: 2500,
    amountMax: 2500,
    amountLabel: "$2,500",
    deadline: "2026-10-15",
    deadlineType: "fixed",
    categories: ["Academic", "National"],
    eligibility: "High school juniors who excel on the PSAT/NMSQT",
    requirements: "Strong PSAT score, academic record, and application materials",
    essayRequired: true,
    effort: "High",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Junior", "Senior"],
    minGpa: 3.5,
    tags: ["Academic", "National", "Merit-Based"],
  },
  {
    id: "seed-coca-cola",
    name: "Coca-Cola Scholars Program",
    sponsor: "Coca-Cola Scholars Foundation",
    url: "https://www.coca-colascholarsfoundation.org/apply/",
    amountMin: 20000,
    amountMax: 20000,
    amountLabel: "$20,000",
    deadline: "2026-10-31",
    deadlineType: "fixed",
    categories: ["Leadership", "Community Service"],
    eligibility: "High school seniors with leadership and service",
    requirements: "3.0+ GPA, leadership, community impact, application essay",
    essayRequired: true,
    effort: "High",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.0,
    tags: ["Leadership", "Service", "National"],
  },
  {
    id: "seed-gates",
    name: "The Gates Scholarship",
    sponsor: "Gates Scholarship Program",
    url: "https://www.thegatesscholarship.org/scholarship",
    amountMin: 50000,
    amountMax: 999999,
    amountLabel: "Full cost of attendance",
    deadline: "2026-09-15",
    deadlineType: "fixed",
    categories: ["Need-Based", "Academic"],
    eligibility: "High-achieving seniors with significant financial need",
    requirements: "3.3+ GPA, Pell-eligible, leadership, minority background",
    essayRequired: true,
    effort: "High",
    renewable: true,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.3,
    needBased: true,
    tags: ["Full Ride", "Need-Based", "National"],
  },
  {
    id: "seed-dell",
    name: "Dell Scholars Program",
    sponsor: "Michael & Susan Dell Foundation",
    url: "https://www.dellscholars.org/",
    amountMin: 20000,
    amountMax: 20000,
    amountLabel: "$20,000 + support services",
    deadline: "2026-12-01",
    deadlineType: "fixed",
    categories: ["Need-Based", "STEM"],
    eligibility: "Seniors facing significant college readiness barriers",
    requirements: "2.4+ GPA, financial need, college readiness plan",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 2.4,
    needBased: true,
    tags: ["Need-Based", "Technology"],
  },
  {
    id: "seed-elks",
    name: "Elks Most Valuable Student Scholarship",
    sponsor: "Elks National Foundation",
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    amountMin: 1000,
    amountMax: 50000,
    amountLabel: "$1,000–$50,000",
    deadline: "2026-11-15",
    deadlineType: "fixed",
    categories: ["Leadership", "Community Service"],
    eligibility: "High school seniors who are U.S. citizens",
    requirements: "Leadership, service, financial need considered, essay",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.0,
    tags: ["Leadership", "Service", "National"],
  },
  {
    id: "seed-hsf",
    name: "Hispanic Scholarship Fund Scholar Program",
    sponsor: "Hispanic Scholarship Fund",
    url: "https://www.hsf.net/scholarship",
    amountMin: 500,
    amountMax: 5000,
    amountLabel: "$500–$5,000",
    deadline: "2026-02-15",
    deadlineType: "fixed",
    categories: ["Diversity", "Academic"],
    eligibility: "Students of Hispanic heritage pursuing higher education",
    requirements: "3.0+ GPA, FAFSA, essay, community involvement",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior", "College student"],
    minGpa: 3.0,
    tags: ["Diversity", "Academic"],
  },
  {
    id: "seed-uncf",
    name: "UNCF General Scholarship",
    sponsor: "United Negro College Fund",
    url: "https://uncf.org/scholarships",
    amountMin: 500,
    amountMax: 5000,
    amountLabel: "$500–$5,000",
    deadline: "2026-03-31",
    deadlineType: "rolling",
    categories: ["Diversity", "Need-Based"],
    eligibility: "African American students with financial need",
    requirements: "2.5+ GPA, demonstrated need, essay",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior", "College student"],
    minGpa: 2.5,
    needBased: true,
    tags: ["Diversity", "Need-Based"],
  },
  {
    id: "seed-regeneron",
    name: "Regeneron Science Talent Search",
    sponsor: "Society for Science",
    url: "https://www.societyforscience.org/regeneron-sts/",
    amountMin: 25000,
    amountMax: 250000,
    amountLabel: "Up to $250,000",
    deadline: "2026-11-08",
    deadlineType: "fixed",
    categories: ["STEM", "Academic"],
    eligibility: "High school seniors conducting original research",
    requirements: "Original STEM research project, application, recommendations",
    essayRequired: true,
    effort: "High",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.0,
    tags: ["STEM", "Research", "Competitive"],
  },
  {
    id: "seed-jack-kent-cooke",
    name: "Jack Kent Cooke College Scholarship",
    sponsor: "Jack Kent Cooke Foundation",
    url: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    amountMin: 55000,
    amountMax: 55000,
    amountLabel: "Up to $55,000/year",
    deadline: "2026-11-17",
    deadlineType: "fixed",
    categories: ["Need-Based", "Academic"],
    eligibility: "High-achieving seniors with financial need",
    requirements: "3.5+ GPA, SAT/ACT scores, financial need, essay",
    essayRequired: true,
    effort: "High",
    renewable: true,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.5,
    needBased: true,
    tags: ["Need-Based", "Academic", "National"],
  },
  {
    id: "seed-horatio-alger",
    name: "Horatio Alger National Scholarship",
    sponsor: "Horatio Alger Association",
    url: "https://scholars.horatioalger.org/",
    amountMin: 25000,
    amountMax: 25000,
    amountLabel: "$25,000",
    deadline: "2026-10-25",
    deadlineType: "fixed",
    categories: ["Need-Based", "Leadership"],
    eligibility: "Seniors who overcame adversity with financial need",
    requirements: "2.0+ GPA, financial need, perseverance, community involvement",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 2.0,
    needBased: true,
    tags: ["Need-Based", "Leadership"],
  },
  {
    id: "seed-burger-king",
    name: "Burger King Scholars Program",
    sponsor: "Burger King Foundation",
    url: "https://www.burgerkingfoundation.org/programs/burger-king-scholars-program",
    amountMin: 1000,
    amountMax: 50000,
    amountLabel: "$1,000–$50,000",
    deadline: "2026-12-15",
    deadlineType: "fixed",
    categories: ["Community Service", "Need-Based"],
    eligibility: "Employees, spouses, or dependents of employees; also community applicants in some regions",
    requirements: "2.5+ GPA, work experience or community service, essay",
    essayRequired: true,
    effort: "Low",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 2.5,
    tags: ["Workforce", "Community"],
  },
  {
    id: "seed-ron-brown",
    name: "Ron Brown Scholar Program",
    sponsor: "Ron Brown Scholar Program",
    url: "https://ronbrown.org/",
    amountMin: 40000,
    amountMax: 40000,
    amountLabel: "$40,000 ($10,000 x 4 years)",
    deadline: "2026-01-09",
    deadlineType: "fixed",
    categories: ["Diversity", "Leadership"],
    eligibility: "African American high school seniors",
    requirements: "Academic excellence, leadership, community service, financial need",
    essayRequired: true,
    effort: "High",
    renewable: true,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.0,
    needBased: true,
    tags: ["Diversity", "Leadership", "National"],
  },
  {
    id: "seed-cameron-impact",
    name: "Cameron Impact Scholarship",
    sponsor: "Bryan Cameron Education Foundation",
    url: "https://www.bryancameroneducationfoundation.org/",
    amountMin: 20000,
    amountMax: 50000,
    amountLabel: "Full tuition (estimated $20K–$50K/year)",
    deadline: "2026-09-12",
    deadlineType: "fixed",
    categories: ["Leadership", "Academic"],
    eligibility: "High school seniors with strong leadership and academics",
    requirements: "3.7+ GPA, leadership, community impact, essay",
    essayRequired: true,
    effort: "High",
    renewable: true,
    locationScope: "National",
    gradeLevels: ["Senior"],
    minGpa: 3.7,
    tags: ["Leadership", "Full Ride", "National"],
  },
  {
    id: "seed-stem-excellence",
    name: "AISES Scholarships (STEM)",
    sponsor: "American Indian Science and Engineering Society",
    url: "https://www.aises.org/students/scholarships",
    amountMin: 1000,
    amountMax: 10000,
    amountLabel: "$1,000–$10,000",
    deadline: "2026-05-31",
    deadlineType: "fixed",
    categories: ["STEM", "Diversity"],
    eligibility: "Native American, Alaska Native, or Native Hawaiian STEM students",
    requirements: "STEM major interest, essay, tribal enrollment or community connection",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "National",
    gradeLevels: ["Senior", "College student"],
    minGpa: 3.0,
    tags: ["STEM", "Diversity"],
  },
  {
    id: "seed-local-community",
    name: "Community Foundation Local Scholarship",
    sponsor: "Community Foundation Network",
    url: "https://www.cfafoundation.org/find-a-community-foundation/",
    amountMin: 1000,
    amountMax: 5000,
    amountLabel: "$1,000–$5,000",
    deadline: "2026-03-01",
    deadlineType: "fixed",
    categories: ["Community Service", "Need-Based"],
    eligibility: "Local residents in your county or region",
    requirements: "Local residency, essay, recommendations, financial need may apply",
    essayRequired: true,
    effort: "Medium",
    renewable: false,
    locationScope: "Local",
    gradeLevels: ["Senior"],
    minGpa: 2.5,
    needBased: true,
    tags: ["Local", "Community"],
  },
];

module.exports = { SEED_SCHOLARSHIPS };
