/**
 * Placeholder college database for the College Match filter.
 * Each entry includes fields used for filtering and admission likelihood scoring.
 */

export const COLLEGES = [
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    city: "Champaign",
    state: "IL",
    region: "Midwest",
    setting: "Suburban",
    type: "Public",
    tuition: 17000,
    size: 37000,
    selectivity: "Target/Match",
    admissionRate: 0.45,
    satAvg: 1350,
    actAvg: 30,
    avgGpa: 3.7,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Computer Science", "Business"],
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    city: "Evanston",
    state: "IL",
    region: "Midwest",
    setting: "Suburban",
    type: "Private",
    tuition: 62000,
    size: 9000,
    selectivity: "Highly Selective",
    admissionRate: 0.07,
    satAvg: 1520,
    actAvg: 34,
    avgGpa: 3.9,
    testPolicy: "Test optional",
    strongMajors: ["Journalism", "Engineering", "Pre-Med"],
  },
  {
    id: "depaul",
    name: "DePaul University",
    city: "Chicago",
    state: "IL",
    region: "Midwest",
    setting: "Urban",
    type: "Private",
    tuition: 42000,
    size: 14000,
    selectivity: "Target/Match",
    admissionRate: 0.68,
    satAvg: 1180,
    actAvg: 26,
    avgGpa: 3.4,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Film", "Computer Science"],
  },
  {
    id: "iit",
    name: "Illinois Institute of Technology",
    city: "Chicago",
    state: "IL",
    region: "Midwest",
    setting: "Urban",
    type: "Private",
    tuition: 48000,
    size: 3000,
    selectivity: "Target/Match",
    admissionRate: 0.58,
    satAvg: 1280,
    actAvg: 28,
    avgGpa: 3.5,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Architecture", "Computer Science"],
  },
  {
    id: "harper",
    name: "Harper College",
    city: "Palatine",
    state: "IL",
    region: "Midwest",
    setting: "Suburban",
    type: "Community College",
    tuition: 4500,
    size: 12000,
    selectivity: "Safety",
    admissionRate: 0.95,
    satAvg: null,
    actAvg: null,
    avgGpa: 2.8,
    testPolicy: "Test optional",
    strongMajors: ["Nursing", "Business", "Liberal Arts"],
  },
  {
    id: "umich",
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    region: "Midwest",
    setting: "Suburban",
    type: "Public",
    tuition: 52000,
    size: 32000,
    selectivity: "Reach",
    admissionRate: 0.18,
    satAvg: 1460,
    actAvg: 33,
    avgGpa: 3.85,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Business", "Pre-Med"],
  },
  {
    id: "wisconsin",
    name: "University of Wisconsin-Madison",
    city: "Madison",
    state: "WI",
    region: "Midwest",
    setting: "Urban",
    type: "Public",
    tuition: 39000,
    size: 36000,
    selectivity: "Reach",
    admissionRate: 0.49,
    satAvg: 1380,
    actAvg: 30,
    avgGpa: 3.75,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Business", "Education"],
  },
  {
    id: "purdue",
    name: "Purdue University",
    city: "West Lafayette",
    state: "IN",
    region: "Midwest",
    setting: "Rural",
    type: "Public",
    tuition: 29000,
    size: 38000,
    selectivity: "Target/Match",
    admissionRate: 0.53,
    satAvg: 1320,
    actAvg: 29,
    avgGpa: 3.65,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Aviation", "Agriculture"],
  },
  {
    id: "ohio-state",
    name: "Ohio State University",
    city: "Columbus",
    state: "OH",
    region: "Midwest",
    setting: "Urban",
    type: "Public",
    tuition: 33000,
    size: 48000,
    selectivity: "Target/Match",
    admissionRate: 0.53,
    satAvg: 1310,
    actAvg: 29,
    avgGpa: 3.6,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Engineering", "Pre-Med"],
  },
  {
    id: "nyu",
    name: "New York University",
    city: "New York",
    state: "NY",
    region: "Northeast",
    setting: "Urban",
    type: "Private",
    tuition: 58000,
    size: 29000,
    selectivity: "Reach",
    admissionRate: 0.12,
    satAvg: 1470,
    actAvg: 33,
    avgGpa: 3.8,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Film", "Computer Science"],
  },
  {
    id: "bu",
    name: "Boston University",
    city: "Boston",
    state: "MA",
    region: "Northeast",
    setting: "Urban",
    type: "Private",
    tuition: 62000,
    size: 18000,
    selectivity: "Reach",
    admissionRate: 0.14,
    satAvg: 1450,
    actAvg: 32,
    avgGpa: 3.78,
    testPolicy: "Test optional",
    strongMajors: ["Communications", "Engineering", "Pre-Med"],
  },
  {
    id: "umass",
    name: "University of Massachusetts Amherst",
    city: "Amherst",
    state: "MA",
    region: "Northeast",
    setting: "Suburban",
    type: "Public",
    tuition: 38000,
    size: 24000,
    selectivity: "Target/Match",
    admissionRate: 0.64,
    satAvg: 1290,
    actAvg: 29,
    avgGpa: 3.55,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Business", "Computer Science"],
  },
  {
    id: "penn-state",
    name: "Penn State University",
    city: "University Park",
    state: "PA",
    region: "Northeast",
    setting: "Rural",
    type: "Public",
    tuition: 36000,
    size: 41000,
    selectivity: "Target/Match",
    admissionRate: 0.55,
    satAvg: 1270,
    actAvg: 28,
    avgGpa: 3.55,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Business", "Agriculture"],
  },
  {
    id: "unc",
    name: "University of North Carolina at Chapel Hill",
    city: "Chapel Hill",
    state: "NC",
    region: "South",
    setting: "Suburban",
    type: "Public",
    tuition: 37000,
    size: 20000,
    selectivity: "Reach",
    admissionRate: 0.17,
    satAvg: 1410,
    actAvg: 31,
    avgGpa: 3.8,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Journalism", "Pre-Med"],
  },
  {
    id: "uga",
    name: "University of Georgia",
    city: "Athens",
    state: "GA",
    region: "South",
    setting: "Suburban",
    type: "Public",
    tuition: 31000,
    size: 30000,
    selectivity: "Target/Match",
    admissionRate: 0.43,
    satAvg: 1320,
    actAvg: 29,
    avgGpa: 3.7,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Journalism", "Agriculture"],
  },
  {
    id: "emory",
    name: "Emory University",
    city: "Atlanta",
    state: "GA",
    region: "South",
    setting: "Suburban",
    type: "Private",
    tuition: 58000,
    size: 7000,
    selectivity: "Highly Selective",
    admissionRate: 0.11,
    satAvg: 1490,
    actAvg: 33,
    avgGpa: 3.85,
    testPolicy: "Test optional",
    strongMajors: ["Pre-Med", "Business", "Public Health"],
  },
  {
    id: "uf",
    name: "University of Florida",
    city: "Gainesville",
    state: "FL",
    region: "South",
    setting: "Suburban",
    type: "Public",
    tuition: 29000,
    size: 35000,
    selectivity: "Reach",
    admissionRate: 0.23,
    satAvg: 1380,
    actAvg: 31,
    avgGpa: 3.75,
    testPolicy: "Test required",
    strongMajors: ["Engineering", "Business", "Pre-Med"],
  },
  {
    id: "ucla",
    name: "UCLA",
    city: "Los Angeles",
    state: "CA",
    region: "West Coast",
    setting: "Urban",
    type: "Public",
    tuition: 44000,
    size: 32000,
    selectivity: "Highly Selective",
    admissionRate: 0.09,
    satAvg: 1430,
    actAvg: 32,
    avgGpa: 3.9,
    testPolicy: "Test optional",
    strongMajors: ["Film", "Engineering", "Pre-Med"],
  },
  {
    id: "usc",
    name: "University of Southern California",
    city: "Los Angeles",
    state: "CA",
    region: "West Coast",
    setting: "Urban",
    type: "Private",
    tuition: 64000,
    size: 21000,
    selectivity: "Reach",
    admissionRate: 0.12,
    satAvg: 1450,
    actAvg: 32,
    avgGpa: 3.82,
    testPolicy: "Test optional",
    strongMajors: ["Film", "Business", "Engineering"],
  },
  {
    id: "oregon-state",
    name: "Oregon State University",
    city: "Corvallis",
    state: "OR",
    region: "West Coast",
    setting: "Suburban",
    type: "Public",
    tuition: 32000,
    size: 26000,
    selectivity: "Safety",
    admissionRate: 0.82,
    satAvg: 1180,
    actAvg: 25,
    avgGpa: 3.3,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Forestry", "Agriculture"],
  },
  {
    id: "stanford",
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    region: "West Coast",
    setting: "Suburban",
    type: "Private",
    tuition: 62000,
    size: 7800,
    selectivity: "Highly Selective",
    admissionRate: 0.04,
    satAvg: 1540,
    actAvg: 35,
    avgGpa: 3.96,
    testPolicy: "Test optional",
    strongMajors: ["Computer Science", "Engineering", "Entrepreneurship"],
  },
  {
    id: "arizona-state",
    name: "Arizona State University",
    city: "Tempe",
    state: "AZ",
    region: "West Coast",
    setting: "Urban",
    type: "Public",
    tuition: 29000,
    size: 65000,
    selectivity: "Safety",
    admissionRate: 0.88,
    satAvg: 1210,
    actAvg: 25,
    avgGpa: 3.35,
    testPolicy: "Test optional",
    strongMajors: ["Business", "Engineering", "Journalism"],
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    city: "Nashville",
    state: "TN",
    region: "South",
    setting: "Urban",
    type: "Private",
    tuition: 60000,
    size: 7200,
    selectivity: "Highly Selective",
    admissionRate: 0.07,
    satAvg: 1510,
    actAvg: 34,
    avgGpa: 3.88,
    testPolicy: "Test optional",
    strongMajors: ["Pre-Med", "Engineering", "Music"],
  },
  {
    id: "iowa-state",
    name: "Iowa State University",
    city: "Ames",
    state: "IA",
    region: "Midwest",
    setting: "Suburban",
    type: "Public",
    tuition: 25000,
    size: 28000,
    selectivity: "Safety",
    admissionRate: 0.88,
    satAvg: 1200,
    actAvg: 25,
    avgGpa: 3.35,
    testPolicy: "Test optional",
    strongMajors: ["Engineering", "Agriculture", "Veterinary Science"],
  },
];

export function getSizeCategory(size) {
  if (size < 5000) return "Small";
  if (size <= 15000) return "Medium";
  return "Large";
}

export function getTuitionRangeLabel(tuition) {
  if (tuition < 15000) return "Under $15,000/year";
  if (tuition <= 30000) return "$15,000–$30,000/year";
  if (tuition <= 50000) return "$30,000–$50,000/year";
  return "$50,000+/year";
}

export function getTuitionRangeKey(tuition) {
  if (tuition < 15000) return "under-15k";
  if (tuition <= 30000) return "15-30k";
  if (tuition <= 50000) return "30-50k";
  return "50k-plus";
}
